apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: vk-paints
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/vk-paints/vkpaints-frontend-service:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config

